<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Traits\ManagesTime;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Fortify\TwoFactorAuthenticatable;

use App\Models\ReferralCode;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable, TwoFactorAuthenticatable, ManagesTime;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'user_type',
        'is_admin',
        'email_verified_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'user_type' => 'string',
            'is_admin' => 'boolean',
        ];
    }

    /**
     * Get the user's initials
     */
    public function initials(): string
    {
        return Str::of($this->name)
            ->explode(' ')
            ->take(2)
            ->map(fn ($word) => Str::substr($word, 0, 1))
            ->implode('');
    }

    /**
     * Check if the user is a lender
     */
    public function isLender(): bool
    {
        return $this->user_type === 'lender';
    }

    /**
     * Check if the user is a borrower
     */
    public function isBorrower(): bool
    {
        return $this->user_type === 'borrower';
    }

    /**
     * Get the referral codes generated by this user
     */
    public function generatedReferralCodes()
    {
        return $this->hasMany(ReferralCode::class, 'created_by_user_id');
    }

    /**
     * Get the referral code used by this user
     */
    public function usedReferralCode()
    {
        return $this->belongsTo(ReferralCode::class, 'used_by_user_id');
    }

    /**
     * Get the loan offers created by this user
     */
    public function loanOffers()
    {
        return $this->hasMany(LoanOffer::class, 'lender_id');
    }

    /**
     * Get the reputation score for this user
     */
    public function reputationScore()
    {
        return $this->hasOne(ReputationScore::class);
    }

    /**
     * Check if the user can apply for a new loan
     */
    public function canApplyForNewLoan()
    {
        // Implement logic based on config safety controls
        $activeLoans = 0; // Placeholder, would count active loans
        return $activeLoans < config('borrower.safety_controls.max_active_loans_per_borrower');
    }
}
